### ISSUE TITLE
issue im facing.

### ISSUE THREAD

**Issue by arpkaz** [NevoSwissa/CL-PizzaThis#1]
Hi bud, Just wanted to let you know I have come across a little issue with your Pizza This job & your Bean Machine job. So basically once server has restarted only half of the PolyZones are able to be used by employees. The other half of them are just non existent 

Example: the coffee glasses in bean machine & the shop in both the PizzaThis and BeanMachine do not show unless script is manually restarted.

(Ps only way i have been able to get around it is by restarting the script after restart).

**Comment by xRoyaltyNLx** [comment]
I have the same issue was looking for solution too

**Comment by NevoSwissa** [comment]
Should be fixed

**Comment by NevoSwissa** [comment]
It’s because qb-target starts before those scripts so you need to put them outside of the [qb] folder and start them on your server.cfg under all the other resources
